# backend:
#  name: github
#  repo: ericthelemur/RecipeWebsiteZola
#  base_url: https://cms-auth.containers.uwcs.co.uk
local_backend: true

backend:
  name: git-gateway

media_folder: "static/images"
collections:
  - name: "recipes"
    label: "Recipes"
    label_singular: 'Recipe'
    folder: "content"
    create: true
    format: toml-frontmatter
    
    filter:
      field: "path"
      pattern: '^.*(?<!_index|_index.md)$'

    nested:
      depth: 100
      summary: '{{title}}'

    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: Extra
        name: extra
        widget: "object"
        fields:
          - {label: "Serves", name: "serves", widget: "string", required: false}
          - {label: "Makes", name: "makes", widget: "string", required: false}
          - {label: "Prep Time", name: "prep", widget: "string", required: false}
          - {label: "Cook Time", name: "cook", widget: "string", required: false}
          - label: "Ingredients"
            name: "ingredients"
            widget: "markdown"
            required: true
            default: ""
            minimal: true
            buttons: ["bold", "heading-three", "bulleted-list"]
            editor_components: []
            modes: ["raw"]

        
      - {label: "Method", name: "body", widget: "markdown"}
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }